export const MODULE_KEYS = {
  HRM: 'hrm',
  ATTENDANCE: 'attendance',
  LEAVE: 'leave',
  PAYROLL: 'payroll',
  PROJECTS: 'projects',
  TASKS: 'tasks',
  TIMESHEETS: 'timesheets',
  TRACKING: 'tracking',
  SCREENSHOTS: 'screenshots',
  REPORTS: 'reports',
  BILLING: 'billing',
  PLATFORM: 'platform',
};

export const FEATURE_KEYS = {
  ADVANCED_REPORTS: 'advanced-reports',
  API_ACCESS: 'api-access',
  FEATURE_FLAGS: 'feature-flags',
  SYSTEM_MONITORING: 'system-monitoring',
};

export const ENTITLEMENT_FEATURES = {
  ALL: 'All Features',
  ATTENDANCE_TRACKING: 'Attendance Tracking',
  BASIC_ACTIVITY_MONITORING: 'Basic Activity Monitoring',
  DETAILED_ACTIVITY_MONITORING: 'Detailed Activity Monitoring',
  SCREENSHOTS: 'Screenshots',
  TASK_MANAGEMENT: 'Task Management',
  PAYROLL: 'Payroll',
  ADVANCED_REPORTS: 'Advanced Reports',
  API_ACCESS: 'API Access',
};

export const MODULE_ENTITLEMENT_MAP = {
  [MODULE_KEYS.HRM]: [],
  [MODULE_KEYS.ATTENDANCE]: [ENTITLEMENT_FEATURES.ATTENDANCE_TRACKING],
  [MODULE_KEYS.LEAVE]: [ENTITLEMENT_FEATURES.ATTENDANCE_TRACKING],
  [MODULE_KEYS.PAYROLL]: [ENTITLEMENT_FEATURES.PAYROLL],
  [MODULE_KEYS.PROJECTS]: [ENTITLEMENT_FEATURES.TASK_MANAGEMENT],
  [MODULE_KEYS.TASKS]: [ENTITLEMENT_FEATURES.TASK_MANAGEMENT],
  [MODULE_KEYS.TIMESHEETS]: [ENTITLEMENT_FEATURES.TASK_MANAGEMENT],
  [MODULE_KEYS.TRACKING]: [
    ENTITLEMENT_FEATURES.BASIC_ACTIVITY_MONITORING,
    ENTITLEMENT_FEATURES.DETAILED_ACTIVITY_MONITORING,
  ],
  [MODULE_KEYS.SCREENSHOTS]: [ENTITLEMENT_FEATURES.SCREENSHOTS],
  [MODULE_KEYS.REPORTS]: [
    ENTITLEMENT_FEATURES.ATTENDANCE_TRACKING,
    ENTITLEMENT_FEATURES.DETAILED_ACTIVITY_MONITORING,
    ENTITLEMENT_FEATURES.ADVANCED_REPORTS,
  ],
  [MODULE_KEYS.BILLING]: [],
  [MODULE_KEYS.PLATFORM]: [],
};

export const FEATURE_ENTITLEMENT_MAP = {
  [FEATURE_KEYS.ADVANCED_REPORTS]: [ENTITLEMENT_FEATURES.ADVANCED_REPORTS],
  [FEATURE_KEYS.API_ACCESS]: [ENTITLEMENT_FEATURES.API_ACCESS],
  [FEATURE_KEYS.FEATURE_FLAGS]: [],
  [FEATURE_KEYS.SYSTEM_MONITORING]: [],
};
